### ISSUE TITLE
Distinction between external/internal datasets

### ISSUE THREAD

**Issue by kaijagahm** [carpentries-incubator/R-help-reprexes#16]
The problem with loading the ratdat package is that it means the datasets are already loaded. In the Data episode, there were some places where we wanted to show the audience "see, we're working with this dataset, but others might not be able to find the csv file on their computer..." I think this was confusing because in fact the audience *could* find the dataset on their computer... by loading the ratdat package!

I think it would be good to have the learners working mostly or partly from a csv for the data portion so they can actually see how hard it is to share a csv file. I.e. consider reading in the `complete` dataset from csv instead of using the version stored in the ratdat package.

**Comment by xortizross** [comment]
Our scripts are currently set up to read-in the csv. I still don't know that I agree, but it's fine.
