### ISSUE TITLE
Submit lesson to incubator

### ISSUE THREAD

**Issue by kaijagahm** [carpentries-incubator/R-help-reprexes#27]
@xortizross has the link to the proposal form

**Comment by xortizross** [comment]
I found more info on this here: https://github.com/carpentries-incubator/proposals?tab=readme-ov-file

**Comment by xortizross** [comment]
Done! I submitted our proposal as an issue following the template. You can find it here: https://github.com/carpentries-incubator/proposals/issues/193 I also added both of you as contributors. I don't foresee any issues.

**Comment by kaijagahm** [comment]
Emailed incubator team to figure out why our lesson isn't showing up on the incubator page despite having the correct topic tags.

**Comment by xortizross** [comment]
Toby has now closed the issue and we are on the incubator
