### ISSUE TITLE
Rethink sections 4.3 and 4.4

### ISSUE THREAD

**Issue by kaijagahm** [carpentries-incubator/R-help-reprexes#46]
section 4.3 maybe way too long—4 exercises and man examples—what are the core concepts we are teaching here?

Allocate time to 4.3 and 4.4 depending on how often people are creating datasets from scratch vs. subsetting

**Comment by xortizross** [comment]
Can I mark this as resolved? @kaijagahm @peterlaurin

**Comment by kaijagahm** [comment]
Yeah I think so
