### ISSUE TITLE
RMarkdown path issue for file read-in

### ISSUE THREAD

**Issue by kaijagahm** [carpentries-incubator/R-help-reprexes#61]
If we move our episodes from .md to .Rmd, then we're going to have a file path issue. Annoyingly, RMarkdown defaults to the directory where it is stored when reading in files, whereas R scripts default to the project root directory. We could use the `here()` package, but I'm afraid that's going to be a lot of cognitive load for our learners. But then they are probably going to be working in R scripts that don't necessarily match our RMarkdown file exactly. How should we handle this?

**Comment by xortizross** [comment]
Resolved based on my previous commit. I just added a data folder in episodes and that is the way other lessons have done it. If we don't like it that way we can discuss further at a later date?
