### ISSUE TITLE
Episode ordering--data before vs. after code?

### ISSUE THREAD

**Issue by kaijagahm** [carpentries-incubator/R-help-reprexes#72]
Moving a note that I wrote in my episode draft over to here for posterity

(note from KG to XOR and PL: While writing this, I started to wonder whether it would make more sense to switch the order of this episode and episode 4, introducing minimal datasets at this point when it becomes clear that we need them.
But I took some time to think, and I actually like it better this way. This way, we've given them the skillset of how to make a minimal dataset, and now they get to apply it (and understand better why to apply it) in this episode. So they get to build on a skill they already have. Vs. if we started with this repro code example, which is kind of high-level conceptual, and then said "oh and by the way you need this other skill, which we will now learn", I have a hunch it'll be harder for them to internalize the overarching workflow.
If you disagree, we can discuss, but right now I'm feeling pretty strongly that we should at least test run it in this order and see if learners agree that it works.)

**Comment by kaijagahm** [comment]
Discussed with @xortizross, who thought we might want to re-order but was willing to try it this way and see. Discussed with @peterlaurin, who agrees with me that this ordering is good for now, but/and points out that we should make efforts to work the road map in throughout the lessons, and also use the code lesson as a chance to incorporate callbacks to all the previous lessons, not just the data lesson.

**Comment by xortizross** [comment]
I think based on today we can agree that the flow works as is for now.
